# Generated by Django 5.0.6 on 2024-06-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='audio_url',
            field=models.URLField(max_length=2000),
        ),
    ]
