# Generated by Django 5.0.6 on 2024-06-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_feeditem_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='transcript_bucket_key',
            field=models.CharField(default='TODO', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
