# Generated by Django 5.0.6 on 2024-06-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_feeditem_transcript_bucket_key_delete_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='duration',
        ),
    ]
