# Generated by Django 5.0.6 on 2024-07-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_cliptopic_usertopic_delete_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
