# Generated by Django 5.0.6 on 2024-07-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_clip_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
