# Generated by Django 5.0.6 on 2024-07-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_enable_fuzzy_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='total_itunes_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
