# Generated by Django 5.0.6 on 2024-07-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_feed_total_itunes_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='audio_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
