# Generated by Django 5.0.6 on 2024-07-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_feeditem_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='audio_bucket_key',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='clip',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='audio_bucket_key',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='transcript_bucket_key',
            field=models.CharField(max_length=2000),
        ),
    ]
