# Generated by Django 5.0.6 on 2024-07-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_clip_audio_bucket_key_alter_clip_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipuserscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
