# Generated by Django 5.0.6 on 2024-07-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_feedtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='language',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
