# Generated by Django 5.0.6 on 2024-07-18 01:53

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_feed_is_english_feed_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="topic_embedding",
            field=models.JSONField(),
        ),
    ]
