# Generated by Django 5.0.6 on 2024-07-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_feed_topic_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='popularity_percentile',
            field=models.FloatField(default=0.0),
        ),
    ]
