# Generated by Django 5.0.6 on 2024-07-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_add_pg_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='topic_embedding',
        ),
    ]
