# Generated by Django 5.0.6 on 2024-07-19 18:02

import pgvector.django.vector
import web.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_feed_topic_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='topic_embedding',
            field=pgvector.django.vector.VectorField(default=web.models.default_vector, dimensions=768),
        ),
    ]
