# Generated by Django 5.0.6 on 2024-07-19 21:16

import pgvector.django.vector
import web.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_remove_celery_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='transcript_embedding',
            field=pgvector.django.vector.VectorField(default=web.models.default_vector, dimensions=768),
        ),
    ]
