# Generated by Django 5.0.6 on 2024-07-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_clip_transcript_embedding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeduserscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feeduserscore',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='feeduserscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clipuserview',
            name='processed',
        ),
        migrations.DeleteModel(
            name='ClipUserScore',
        ),
        migrations.DeleteModel(
            name='FeedUserScore',
        ),
    ]
