# Generated by Django 5.0.6 on 2024-08-02 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_feeduserscore_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['created_at'], name='web_clip_created_330f14_idx'),
        ),
        migrations.AddIndex(
            model_name='clipuserview',
            index=models.Index(fields=['created_at'], name='web_clipuse_created_6ad26a_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['total_itunes_ratings'], name='web_feed_total_i_f103f1_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['is_english'], name='web_feed_is_engl_a4c5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['popularity_percentile'], name='web_feed_popular_d7d3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['posted_at'], name='web_feedite_posted__706d9d_idx'),
        ),
    ]
