# Generated by Django 5.0.6 on 2024-08-02 23:40

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_clip_web_clip_created_330f14_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['feed_item', 'created_at'], name='web_clip_feed_it_116b19_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['feed_item', 'created_at', 'name', 'summary'], name='web_clip_feed_it_481593_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['transcript_embedding'], m=16, name='clip_transcript_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='clipuserview',
            index=models.Index(fields=['user', 'clip', 'created_at'], name='web_clipuse_user_id_ed341c_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['is_english', 'popularity_percentile'], name='web_feed_is_engl_4e9a47_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['topic_embedding'], m=16, name='feed_topic_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['feed', 'posted_at'], name='web_feedite_feed_id_ab83cd_idx'),
        ),
        migrations.AddIndex(
            model_name='feedtopic',
            index=models.Index(fields=['feed', 'text'], name='web_feedtop_feed_id_54acd5_idx'),
        ),
        migrations.AddIndex(
            model_name='feeduserinterest',
            index=models.Index(fields=['user', 'feed', 'is_interested'], name='web_feeduse_user_id_faabf2_idx'),
        ),
        migrations.AddIndex(
            model_name='feeduserinterest',
            index=models.Index(fields=['feed', 'is_interested'], name='web_feeduse_feed_id_7a80df_idx'),
        ),
    ]
