# Generated by Django 5.0.6 on 2024-08-03 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_clip_web_clip_feed_it_116b19_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['feed_item'], name='web_clip_feed_it_9632a0_idx'),
        ),
        migrations.AddIndex(
            model_name='clipuserview',
            index=models.Index(fields=['clip'], name='web_clipuse_clip_id_ab9146_idx'),
        ),
        migrations.AddIndex(
            model_name='clipuserview',
            index=models.Index(fields=['user'], name='web_clipuse_user_id_16740c_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['feed'], name='web_feedite_feed_id_fb7e77_idx'),
        ),
    ]
