# Generated by Django 5.0.6 on 2024-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_clip_web_clip_feed_it_9632a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='artwork_bucket_key',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
