# Generated by Django 5.0.6 on 2024-08-09 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_feed_artwork_bucket_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.category')),
            ],
            options={
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='ClipCategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.clip')),
            ],
            options={
                'unique_together': {('clip', 'category')},
            },
        ),
    ]
