# Generated by Django 5.0.6 on 2024-08-12 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_usercategoryscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipcategoryscore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clipcategoryscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercategoryscore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercategoryscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
