# Generated by Django 5.0.6 on 2024-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_clipcategoryscore_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='should_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='user_friendly_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='user_friendly_parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
