# Generated by Django 5.0.6 on 2024-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_category_should_display_category_user_friendly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='should_display',
            field=models.BooleanField(default=False),
        ),
    ]
