# Generated by Django 5.0.6 on 2024-08-28 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipTopicScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.clip')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.topic')),
            ],
            options={
                'unique_together': {('clip', 'topic')},
            },
        ),
    ]
