# Generated by Django 5.0.6 on 2024-08-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_cliptopicscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category'),
        ),
    ]
