# Generated by Django 5.0.6 on 2024-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_remove_category_should_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='topics', to='web.category'),
        ),
    ]
