# Generated by Django 5.0.6 on 2024-08-29 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='categories',
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='web.topic'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent'], name='web_topic_parent__8d4eaa_idx'),
        ),
    ]
