# Generated by Django 5.0.6 on 2024-09-05 21:06

import pgvector.django.vector
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_remove_topic_categories_topic_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='embedding',
            field=pgvector.django.vector.VectorField(default=web.models.default_vector, dimensions=768),
        ),
    ]
