# Generated by Django 5.0.6 on 2024-09-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='should_display',
            field=models.BooleanField(default=False),
        ),
    ]
